version: "3.7"
services:
  proxy:
    build:
      context: ./envoy-proxy/
      dockerfile: Dockerfile
    networks:
      - envoymesh
    ports:
      - "8000:8000"

  web_service:
    build:
      context: ./web-server/
      dockerfile: Dockerfile
    networks:
      - envoymesh
    ports:
      - "8080:80"

networks:
  envoymesh: {}
